[[donor]]
customer_id = "every.org:f38d804d-7ac9-4bc2-a623-64770ae11d25"
link = "https://www.fslabs.ca"
logo = "Foresight_Spatial_Labs.svg"

[[donor]]
customer_id = "every.org:4e4cb5f3-5346-4ead-99a8-db7d094f45f3"
link = "https://github.com/hazelthewitch"
name = "Aurelia Rella"

[[donor]]
customer_id = "stripe:cus_PihVbmEUk0vBkO"
logo = "dead_money.png"
link = "https://deadmoney.gg"
square_logo = true

[[donor]]
customer_id = "stripe:cus_Pl90EWRu326v6N"
logo = "cblogo.svg"

[[donor]]
customer_id = "stripe:cus_QCZaYjp4CCulkK"
logo = "holonautic.png"
logo_scale = 0.45

[[donor]]
customer_id = "stripe:cus_QIGvoRCqPjeUX0"
logo = "keygen.svg"

[[donor]]
customer_id = "stripe:cus_Q5reWVu1n5bNFp"
logo = "roids.png"
square_logo = true

[[donor]]
customer_id = "stripe:cus_QeVAq5EY70jHv8"
logo = "rustunit.png"
square_logo = true

[[donor]]
customer_id = "every.org:4ecf71b1-792c-430b-a722-4fb081c02126"
name = "rudderbucky"

[[donor]]
customer_id = "every.org:b5b96bb4-a0f1-45ff-b7c0-011028bc7bbc"
name = "IceSentry"

[[donor]]
customer_id = "every.org:ef5c3e95-8f47-4b8d-8ad6-e59c776074cd"
logo = "navier-ai.png"
link = "https://navier.ai/"

[[donor]]
customer_id = "every.org:20c63206-7f73-4753-83fb-3f04ef462f60"
anonymize = true

[[donor]]
customer_id = "every.org:9f5be61b-d183-4301-84a8-b57858802be1"
name = "RyeToastyO"

[[donor]]
customer_id = "every.org:4d68d1e5-8ca6-4fa8-898e-fd7d6c7a55b0"
name = "Saveliy Yusufov"
link = "https://github.com/smu160"

[[donor]]
customer_id = "every.org:8981a58f-044f-45f4-a454-da2d902cb2b0"
name = "Alan Jesser"

[[donor]]
customer_id = "stripe:cus_Pk1d910e98zov2"
name = "Petr Kharitonov"

[[donor]]
customer_id = "every.org:75b7e254-8374-4a65-8c63-ffe26166e48c"
logo = "scorewarrior.svg"
link = "https://scwr.gg/bevy"
logo_scale = 0.7

[[donor]]
customer_id = "every.org:ebc41ad1-d4cb-4216-a60c-f30b170fcd2a"
name = "Mysvac"

[[donor]]
customer_id = "every.org:c2eac8de-e69f-41de-8a31-11f43b55932a"
logo = "pouncelight.png"
link = "https://pouncelight.games/"
square_logo = true
